
services:
  dash-server:
    build: dash-server
    ports:
      - "2020:80"
    networks:
      mynetwork:
  istream-player:
    build: istream-player
    # entrypoint: ["iplay", "-h"]
    entrypoint: ["iplay", "-i", "http://ha-proxy/longdress/output.mpd", "--mod_abr", "bandwidth", "--mod_analyzer", "playback_pc"]
    # deploy: 
    #   mode: replicated
    #   replicas: 2
    # command:
      # - "sh"
      # - "-c"
      # - | 
      #   curl --retry 10 -f --retry-all-errors --retry-delay 1 \
      #   -v -o /dev/null http://edge-server/health && \
      #   iplay -i http://dash-server/Aspen/output.mpd --run_dir run-dir --mod_abr hybrid --mod_analyzer file_saver
    # ports:
    #   - "4040:80"
    depends_on:
      - dash-server
      - ha-proxy
    networks:
      mynetwork:
    # volumes:
    #   - ~/your/local/directory:/src/run-dir:rw
    #   - ~/your/local/directory:/src/plot-dir:rw
  ha-proxy:
    build: ha-proxy
    ports:
      - "9090:80"
      - "8404:8404"
    cap_add:
      - NET_ADMIN
    depends_on:
      - dash-server
    networks:
      mynetwork:
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16