
services:
  dash-server:
    image: hadirad/vvdash-server:latest
    # build: dash-server
    ports:
      - "2020:80"
    networks:
      mynetwork:
  istream-player:
    image: hadirad/vvdash-client:latest
    # build: istream-player
    # entrypoint: ["iplay", "-h"]
    entrypoint: ["iplay", "-i", "http://ha-proxy/longdress/output.mpd", "--mod_abr", "bandwidth", "--mod_analyzer", "data_collector"]
    depends_on:
      - dash-server
      - ha-proxy
    networks:
      mynetwork:
  ha-proxy:
    image: hadirad/vvdash-haproxy:latest
    # build: ha-proxy
    ports:
      - "9090:80"
      - "8404:8404"
    cap_add:
      - NET_ADMIN
    depends_on:
      - dash-server
    networks:
      mynetwork:
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16